### ISSUE TITLE
4.2以降の端末について

### ISSUE THREAD

**Issue by AyaneChiang** [kongbab04/ListViewTable#1]
とうも
あたしのプロジェクトはこの機能を利用しました（LinearLayoutのonLayout時にTableLayoutを調整する）
4.3と4.4の端末は問題ありませんが、
4.2と4.1のHeaderの横幅は自動整列ができない

4.2～4.1の端末に支援することができますか

**Comment by kongbab04** [comment]
@Hyouun Issue登録ありがとうございます。
4.2, 4.1の実機が手元になくて、該当の現象の確認が出来ませんでした。
(ＡＶＤ　Ｍａｎａｇｅｒからは、二つのＯＳとも特に問題ありませんでした。)

ListViewTableのonLayoutのcolWidthsに横幅は問題なく取得されているのでしょうか？

**Comment by AyaneChiang** [comment]
お返事ありがとう
はい、横幅は取得されています。
じゃあ…こっちの問題かな(´･ω･`)
また報告します

# 

問題が見つかった！
onLayoutの時、colWidthsの横幅は取られましたけど、画面は更新しない
もう一度画面を更新すると（画面回転とか）、自動整列ができる
AsyncTaskの中でTableLayoutを使う、このIssueは出る
詳しい説明と解決方法はこちら
http://stackoverflow.com/questions/8613465/android-onlayout-and-asynctask-does-not-work-together
